{
  description = "NixOS Flake by/for Ishansh Lal";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    # nixos-hardware.url = "github:NixOS/nixos-hardware/master"; # no hardware config for HP Omen 15
    quickshell = {
      url = "github:quickshell-mirror/quickshell";
      inputs.nixpkgs.follows = "nixpkgs";
    };

  };

  outputs = { self, nixpkgs, ... }@inputs:{
    nixosConfigurations = {
      "NixOS-Laptop" = nixpkgs.lib.nixosSystem {
        specialArgs = { inherit inputs; };
        system = "x86_64-linux";
        modules = [
          {
            # Override
            networking.hostName = "NixOS-Laptop"; # Same as <config> in nixosConfigurations.<config>
            time.timeZone = "Asia/Kolkata";
          }

          # System configuration (system packages, hardware config etc.)
          /etc/nixos/hardware-configuration.nix # require --impure # generated by nixos generate config
          ./system/Laptop

          # All users
          ./users/ilal
        ];
      };
    };
  };
}
