{
  description = "NixOS Flake by/for Ishansh Lal";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    nixpkgs-stable.url = "github:NixOS/nixpkgs/nixos-25.05";
  };

  outputs = { self, nixpkgs, nixpkgs-stable, ... }@inputs:{
    nixosConfigurations = {
      "NixOS-Laptop" = let
        system = "x86_64-linux";
        pkgs-stable = import nixpkgs-stable { inherit system; };
      in nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = {
          inherit inputs pkgs-stable;
        };
        modules = [
          {
            # Override
            networking.hostName = "NixOS-Laptop"; # Same as <config> in nixosConfigurations.<config>
            time.timeZone = "Asia/Kolkata";
          }

          # System configuration (system packages, hardware config etc.)
          /etc/nixos/hardware-configuration.nix # require --impure # generated by nixos generate config
          ./system/Laptop

          # All users
          ./users/ilal
        ];
      };
    };
  };
}
