$Font = "CaskaydiaCove Nerd Font"

general {
    hide_cursor = false
}

# enable fingerprint authentication, if available
auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $Font

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $Font

    position = -30, -150
    halign = right
    valign = top
}

# USER
label {
    monitor =
    text = Hi, $USER
    font_size = 25
    font_family = $Font
    color = rgb(200, 160, 160)

    position = 0, +40
    halign = center
    valign = center
}

# PASSWORD
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    placeholder_text = Input password...
    fail_text = $PAMFAIL

    dots_size = 0.5
    dots_spacing = 0.3
    dots_rounding = 10

    position = 0, -40
    halign = center
    valign = center
}

# Reboot
label {
    monitor =
    text = 󰜉.
    color = rgb(160, 160, 200)
    font_size = 32
    onclick = reboot now
    position = -120, -125
    halign = center
    valign = center
}

# Shutdown
label {
    monitor =
    text = 󰐥.
    color = rgb(160, 160, 200)
    font_size = 32
    onclick = shutdown now
    position = -40, -125
    halign = center
    valign = center
}

# SUSPEND
label {
    monitor =
    text = 󰤄.
    color = rgb(160, 160, 200)
    font_size = 32
    onclick = systemctl suspend
    position = +40, -125
    halign = center
    valign = center
}

# LOGOUT
label {
    monitor =
    text = 󰍃.
    color = rgb(160, 160, 200)
    font_size = 32
    onclick = hyprctl dispatch exit
    position = +120, -125
    halign = center
    valign = center
}
